### ISSUE TITLE
Spécifier fichier étudiants

### ISSUE THREAD

**Issue by prevostcorentin** [Elifinanc/ProgrammeDailyStandup#5]
Afin d'améliorer la modularité et l'utilité du programme, faire en sorte que l'on puisse passer un nom de fichier en argument ligne de commande afin que le programme ouvre celui-ci comme étant le fichier contenant les étudiants. 

Voici un exemple d'utilisation:
```
C:\> DailyStandUpProgram.exe --file students.txt
```

Ou

```
C:\> DailyStandUpProgram.exe -f students.txt
```

**Comment by Iurii-Antoniuk** [comment]
sds
